using System;
using System.Reflection;
using Kitware.mummy.Runtime;

namespace Kitware.VTK
{
	/// <summary>
	///    vtkSMPMergePolyDataHelper
	/// </summary>
	/// <remarks>
	///    Utility class for merging poly data in parallel
	/// This class is designed as a utility class to help merging of poly data
	/// generated by filters that generate multiple polydata outputs and the associated
	/// locators. It requires that the filter uses vtkSMPMergePoints which creates
	/// a number of necessary data structures.
	/// </remarks>
	// Token: 0x02000425 RID: 1061
	public class vtkSMPMergePolyDataHelper : WrappedObject
	{
		/// <summary>
		/// Automatically generated type registration mechanics.
		/// </summary>
		// Token: 0x0600C7E1 RID: 51169 RVA: 0x00116077 File Offset: 0x00114277
		static vtkSMPMergePolyDataHelper()
		{
			Methods.RegisterType(Assembly.GetExecutingAssembly(), vtkSMPMergePolyDataHelper.MRClassNameKey, Type.GetType("Kitware.VTK.vtkSMPMergePolyDataHelper"));
		}

		/// <summary>
		/// Automatically generated constructor - called from generated code.
		/// DO NOT call directly.
		/// </summary>
		// Token: 0x0600C7E2 RID: 51170 RVA: 0x0011609F File Offset: 0x0011429F
		public vtkSMPMergePolyDataHelper(IntPtr rawCppThis, bool callDisposalMethod, bool strong) : base(rawCppThis, callDisposalMethod, strong)
		{
		}

		/// <summary>
		/// Automatically generated protected Dispose method - called from
		/// public Dispose or the C# destructor. DO NOT call directly.
		/// </summary>
		// Token: 0x0600C7E3 RID: 51171 RVA: 0x001160AD File Offset: 0x001142AD
		protected override void Dispose(bool disposing)
		{
			base.Dispose(disposing);
		}

		/// <summary>
		/// Automatically generated type registration mechanics.
		/// </summary>
		// Token: 0x04000EDB RID: 3803
		public new const string MRFullTypeName = "Kitware.VTK.vtkSMPMergePolyDataHelper";

		/// <summary>
		/// Automatically generated type registration mechanics.
		/// </summary>
		// Token: 0x04000EDC RID: 3804
		public new static readonly string MRClassNameKey = "class vtkSMPMergePolyDataHelper";
	}
}
